apiVersion: v1
kind: Secret
metadata:
  name: registrypullsecret
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CgkJCSJhdXRoIjogIllXMTZZWEl4TWpNNlFXcHBXbUZ3WVhJeE1qTT0iCgkJfQoJfQp9
type: kubernetes.io/dockerconfigjson